apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskboard-frontend
  template:
    metadata:
      labels:
        app: taskboard-frontend
    spec:
      containers:
      - name: frontend
        image: yourdockerhubusername/taskboard-frontend:latest
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
  - port: 80
    targetPort: 5173
  selector:
    app: taskboard-frontend
  type: LoadBalancer
